/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MainRouteImport } from './routes/_main'
import { Route as MainIndexRouteImport } from './routes/_main/index'
import { Route as MainBooksRouteImport } from './routes/_main/books'
import { Route as MainSearchRouteImport } from './routes/_main/search'
import { Route as MainHadis40IndexRouteImport } from './routes/_main/hadis40/index'
import { Route as MainBookSlugIndexRouteImport } from './routes/_main/book/$slug/index'

const MainRoute = MainRouteImport.update({
  id: '/_main',
  getParentRoute: () => rootRouteImport,
} as any)
const MainIndexRoute = MainIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MainRoute,
} as any)
const MainBooksRoute = MainBooksRouteImport.update({
  id: '/books',
  path: '/books',
  getParentRoute: () => MainRoute,
} as any)
const MainSearchRoute = MainSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => MainRoute,
} as any)
const MainHadis40IndexRoute = MainHadis40IndexRouteImport.update({
  id: '/hadis40/',
  path: '/hadis40/',
  getParentRoute: () => MainRoute,
} as any)
const MainBookSlugIndexRoute = MainBookSlugIndexRouteImport.update({
  id: '/book/$slug/',
  path: '/book/$slug/',
  getParentRoute: () => MainRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof MainIndexRoute
  '/books': typeof MainBooksRoute
  '/search': typeof MainSearchRoute
  '/hadis40/': typeof MainHadis40IndexRoute
  '/book/$slug/': typeof MainBookSlugIndexRoute
}
export interface FileRoutesByTo {
  '/books': typeof MainBooksRoute
  '/search': typeof MainSearchRoute
  '/': typeof MainIndexRoute
  '/hadis40': typeof MainHadis40IndexRoute
  '/book/$slug': typeof MainBookSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_main': typeof MainRouteWithChildren
  '/_main/books': typeof MainBooksRoute
  '/_main/search': typeof MainSearchRoute
  '/_main/': typeof MainIndexRoute
  '/_main/hadis40/': typeof MainHadis40IndexRoute
  '/_main/book/$slug/': typeof MainBookSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/books' | '/search' | '/hadis40/' | '/book/$slug/'
  fileRoutesByTo: FileRoutesByTo
  to: '/books' | '/search' | '/' | '/hadis40' | '/book/$slug'
  id:
    | '__root__'
    | '/_main'
    | '/_main/books'
    | '/_main/search'
    | '/_main/'
    | '/_main/hadis40/'
    | '/_main/book/$slug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  MainRoute: typeof MainRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_main': {
      id: '/_main'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main/': {
      id: '/_main/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MainIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/books': {
      id: '/_main/books'
      path: '/books'
      fullPath: '/books'
      preLoaderRoute: typeof MainBooksRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/search': {
      id: '/_main/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof MainSearchRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/hadis40/': {
      id: '/_main/hadis40/'
      path: '/hadis40'
      fullPath: '/hadis40/'
      preLoaderRoute: typeof MainHadis40IndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/book/$slug/': {
      id: '/_main/book/$slug/'
      path: '/book/$slug'
      fullPath: '/book/$slug/'
      preLoaderRoute: typeof MainBookSlugIndexRouteImport
      parentRoute: typeof MainRoute
    }
  }
}

interface MainRouteChildren {
  MainBooksRoute: typeof MainBooksRoute
  MainSearchRoute: typeof MainSearchRoute
  MainIndexRoute: typeof MainIndexRoute
  MainHadis40IndexRoute: typeof MainHadis40IndexRoute
  MainBookSlugIndexRoute: typeof MainBookSlugIndexRoute
}

const MainRouteChildren: MainRouteChildren = {
  MainBooksRoute: MainBooksRoute,
  MainSearchRoute: MainSearchRoute,
  MainIndexRoute: MainIndexRoute,
  MainHadis40IndexRoute: MainHadis40IndexRoute,
  MainBookSlugIndexRoute: MainBookSlugIndexRoute,
}

const MainRouteWithChildren = MainRoute._addFileChildren(MainRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  MainRoute: MainRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
